### PR TITLE
Enable HiDPI support [INSTALLER]

### PR DESCRIPTION
**Pull request by iakov**
Enables HiDPI. But on macOS Mojave with FullHD monitor fonts became too small. What with other systems?
Screenshot 2019-09-05 at 01 54 46

### CODE REVIEW

**Comment by iakov** [comment]
Xenial, FullHD -- fine, no changes.

**Comment by ilaforer** [comment]
10 win 1803 в режиме 1600х900 все ок

**Comment by ilyashir** [comment]
1920х1080 на Win10 1903 -- все отлично.

**Comment by shirokolobov** [comment]
1920х1080 на Win10 1803 - всё ОК.
1280х1024 на Win10 1803 - всё ОК.

**Pull request merged**
